package com.policebodycam.police_body_cam

/**
 * Pure, framework-independent volume-button gesture detector: double
 * press vs. long press vs. Android's own hardware key-repeat.
 * Deliberately has ZERO android.* imports so it is testable with plain
 * JUnit and a fake clock/scheduler (see VolumeGestureDetectorTest) --
 * deterministically, without Robolectric, an emulator, or root (a real
 * physical long-press hold could not be injected via adb without root on
 * the test device -- see the physical-verification report).
 * MainActivity.kt is a thin adapter that feeds real KeyEvent fields into
 * this and consumes an event only when it returns true from [onKeyDown].
 *
 * Recognized gestures are reported via [onTrigger] as (keyIsVolumeUp,
 * kind) where kind is "double" or "long" -- this class only recognizes
 * gestures; it has no idea what a "recording" is. What each gesture DOES
 * (start front/back emergency recording, or stop an active one) is
 * decided entirely in Dart by
 * lib/utils/volume_trigger_logic.dart::decideVolumeTriggerAction, kept
 * symmetrically pure and unit-tested on that side for exactly the same
 * reason.
 */
class VolumeGestureDetector(
    private val doublePressWindowMs: Long = 600L,
    private val longPressThresholdMs: Long = 600L,
    /** Injectable so tests can use a fake, manually-advanced clock. */
    private val now: () -> Long,
    /**
     * Injectable so tests can use a fake scheduler that never actually
     * sleeps -- production passes a real Handler.postDelayed-backed
     * implementation (see MainActivity.kt).
     */
    private val schedule: (delayMs: Long, run: () -> Unit) -> Cancellable,
    private val onTrigger: (keyIsVolumeUp: Boolean, kind: String) -> Unit,
) {
    fun interface Cancellable {
        fun cancel()
    }

    // Independent bookkeeping per key (true = VOLUME_UP, false = VOLUME_DOWN).
    // Absent from the map means "no eligible previous press" -- deliberately
    // NOT represented by a 0/sentinel timestamp, which a fake/test clock
    // (or, in principle, a device very close to the epoch) could collide
    // with: a real bug this class's own test suite caught (an absent-key
    // default of 0 made `t - 0` fall inside the double-press window for any
    // t <= windowMs, wrongly treating a key's very FIRST press as
    // completing a double).
    private val lastDownAtByKey = mutableMapOf<Boolean, Long>()
    private val pendingLongPressByKey = mutableMapOf<Boolean, Cancellable>()

    /**
     * Call on ACTION_DOWN with the event's real repeatCount. Returns true
     * if this specific DOWN event should be consumed (never let it also
     * nudge system volume) -- true only for the down that completes a
     * recognized double press; a long press instead fires later, from the
     * scheduled timer, with nothing left for the caller to consume at
     * that point.
     */
    fun onKeyDown(keyIsVolumeUp: Boolean, repeatCount: Int): Boolean {
        // Android's own auto-repeat (repeatCount > 0, generated by the OS
        // while a key stays physically down) must NEVER be treated as a
        // fresh press -- this is the actual bug fix: a single held press
        // was previously miscounted as a second press via these events,
        // falsely firing a double-press action from what the user
        // experienced as one continuous hold. Long-press detection below
        // uses its own independent timer keyed off the ORIGINAL down
        // (repeatCount == 0), not this stream, so repeat events are pure
        // no-ops here.
        if (repeatCount > 0) return false

        val t = now()
        val lastDownAt = lastDownAtByKey[keyIsVolumeUp]
        // Cancel any stale pending long-press check for this key -- a
        // fresh DOWN always supersedes whatever came before it.
        pendingLongPressByKey.remove(keyIsVolumeUp)?.cancel()

        if (lastDownAt != null && t - lastDownAt in 1..doublePressWindowMs) {
            // Second physical press of a genuine double, within the
            // window -- fires exactly once, consumed so it never also
            // nudges system volume.
            lastDownAtByKey.remove(keyIsVolumeUp)
            onTrigger(keyIsVolumeUp, "double")
            return true
        }

        // First press of a possible pair, and simultaneously the start of
        // a possible long press. Schedule a one-shot check: if the key is
        // still down longPressThresholdMs later (no matching ACTION_UP
        // having cancelled it via onKeyUp), this was a long press, fired
        // exactly once regardless of how many repeatCount>0 events arrive
        // in the meantime (they're ignored above, never reaching here).
        lastDownAtByKey[keyIsVolumeUp] = t
        pendingLongPressByKey[keyIsVolumeUp] = schedule(longPressThresholdMs) {
            pendingLongPressByKey.remove(keyIsVolumeUp)
            // A press that just fired as a long press must never ALSO be
            // eligible to complete a double press if the key is tapped
            // again immediately after release -- clear the down timestamp
            // entirely (not reset to a sentinel) so the next tap always
            // starts its own, fresh double-press window.
            lastDownAtByKey.remove(keyIsVolumeUp)
            onTrigger(keyIsVolumeUp, "long")
        }

        // Never consume the first press of a pair (or a lone/held press)
        // -- only a recognized double (above) or long (via the scheduled
        // callback) fires an action, so an isolated single quick tap still
        // behaves as normal system volume adjustment and produces no app
        // action, exactly as required.
        return false
    }

    /** Call on ACTION_UP: cancels a pending long-press check if the key was released before the threshold. */
    fun onKeyUp(keyIsVolumeUp: Boolean) {
        pendingLongPressByKey.remove(keyIsVolumeUp)?.cancel()
    }

    /** Cancels every pending timer -- call from Activity.onDestroy so nothing fires after teardown. */
    fun dispose() {
        pendingLongPressByKey.values.forEach { it.cancel() }
        pendingLongPressByKey.clear()
    }
}
